#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const child_process = require('node:child_process');

process.chdir(__dirname + '/..');

if (!fs.existsSync('caches/pokemon-showdown')) {
	child_process.execSync('git clone https://github.com/CoruptedUsername/pokemon-showdown.git', {
		cwd: 'caches',
		b: 'sprite-test',
	});
}

process.stdout.write("Syncing data from Git repository... ");
child_process.execSync('git pull', { cwd: 'caches/pokemon-showdown' });
child_process.execSync('npm run build', { cwd: 'caches/pokemon-showdown' });
console.log("DONE");

const Dex = require('../caches/pokemon-showdown/dist/sim/dex').Dex;
const CompoundWordNames = require('../caches/pokemon-showdown/dist/data/aliases').CompoundWordNames;
const toID = Dex.toID;
process.stdout.write("Loading gen 6 data... ");
Dex.includeData();
console.log("DONE");

function es3stringify(obj) {
	const buf = JSON.stringify(obj);
	return buf.replace(/"([A-Za-z][A-Za-z0-9]*)":/g, (fullMatch, key) => (
		['return', 'new', 'delete'].includes(key) ? fullMatch : `${key}:`
	));
}

function requireNoCache(pathSpec) {
	delete require.cache[require.resolve(pathSpec)];
	return require(pathSpec);
}

/*********************************************************
 * Initialize BattleTeamBuilder
 *********************************************************/

const BattleTeambuilderTable = {};

BattleTeambuilderTable.formats = {};
BattleTeambuilderTable.sprites = {};

let modsWithSprites = []

let oldSpritesFolderDeleted = false;

for (const modDex in Dex.dexes) {
	let hasSprites = Dex.mod(modDex).data.Sprites?.monSprites !== undefined ||
		Dex.mod(modDex).data.Sprites?.itemSprites !== undefined ||
		Dex.mod(modDex).data.Sprites?.typeSprites !== undefined
	if (hasSprites) {
		BattleTeambuilderTable.sprites[modDex] = {};
		if (!oldSpritesFolderDeleted) {
			fs.rmSync('./play.pokemonshowdown.com/sprites/mods', {recursive: true, force: true});
			oldSpritesFolderDeleted = true;
		}
		fs.cpSync(`./caches/pokemon-showdown/data/mods/${modDex}/sprites`, `./play.pokemonshowdown.com/sprites/mods/${modDex}`, {recursive: true, force: true});
		if (Dex.mod(modDex).data.Sprites?.monSprites !== undefined) {
			BattleTeambuilderTable.sprites[modDex]["monSpriteSettings"] = {
				"backDistinction": Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
				"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
				"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
				"defaultSpritesGen": Dex.mod(modDex).data.Sprites.monSprites.defaultSpritesGen,
			}
			BattleTeambuilderTable.sprites[modDex]["monSprites"] = {};
			if (Dex.mod(modDex).data.Sprites.monSprites.autogenCustoms) {
				console.log("Autogenning custom sprites for ", modDex);
				let monsToGen = fs.readdirSync(`./play.pokemonshowdown.com/sprites/mods/${modDex}${Dex.mod(modDex).data.Sprites.monSprites.monsDirectory}`)
				for (const mon of monsToGen) {
					BattleTeambuilderTable.sprites[modDex]["monSprites"][toID(mon)] = {
						"spriteType": "custom",
						"path": Dex.mod(modDex).data.Sprites.monSprites.monsDirectory + "/" + mon,
						"backDistinction": Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
						"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
						"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
						"separateTeambuilderSprites": Dex.mod(modDex).data.Sprites.monSprites.separateTeambuilderSprites,
					}
				}
			}
			for (const mon in Dex.mod(modDex).data.Sprites.monSprites?.customSprites) {
				if (typeof(Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon]) === "string") {
					BattleTeambuilderTable.sprites[modDex]["monSprites"][mon] = {
						"spriteType": "custom",
						"path": Dex.mod(modDex).data.Sprites.monSprites.monsDirectory + Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon],
						"backDistinction": Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
						"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
						"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
						"separateTeambuilderSprites": Dex.mod(modDex).data.Sprites.monSprites.separateTeambuilderSprites,
					}
				} else {
					BattleTeambuilderTable.sprites[modDex]["monSprites"][mon] = {
						"spriteType": "custom",
						"path": Dex.mod(modDex).data.Sprites.monSprites.monsDirectory + Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].spriteDirectory,
						"backDistinction": Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].backDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].backDistinction: Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
						"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].shinyDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].shinyDistinction: Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
						"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].femaleDistinction: Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
						"separateTeambuilderSprites": Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].separateTeambuilderSprites ? Dex.mod(modDex).data.Sprites.monSprites?.customSprites[mon].separateTeambuilderSprites: Dex.mod(modDex).data.Sprites.monSprites.separateTeambuilderSprites,
					}

				}
			}
			for (const mon in Dex.mod(modDex).data.Sprites.monSprites?.copySprites) {
				if (typeof(Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon]) === "string") {
					BattleTeambuilderTable.sprites[modDex]["monSprites"][mon] = {
						"spriteType": "copy",
						"copySpriteMon": toID(Dex.mod(modDex).data.Sprites.monSprites.copySprites[mon]),
						"copySpriteGen": Dex.mod(modDex).data.Sprites.monSprites.defaultSpritesGen,
						"backDistinction": Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
						"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
						"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
					}
				} else {
					BattleTeambuilderTable.sprites[modDex]["monSprites"][mon] = {
						"spriteType": "copy",
						"copySpriteMon": toID(Dex.mod(modDex).data.Sprites.monSprites.copySprites[mon].copySpriteMon),
						"copySpriteGen": Dex.mod(modDex).data.Sprites.monSprites.copySprites[mon].copySpriteGen ? Dex.mod(modDex).data.Sprites.monSprites.copySprites[mon].copySpriteGen : Dex.mod(modDex).data.Sprites.monSprites?.defaultSpritesGen,
						"backDistinction": Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].backDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].backDistinction: Dex.mod(modDex).data.Sprites.monSprites.backDistinction,
						"shinyDistinction": Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].shinyDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].shinyDistinction: Dex.mod(modDex).data.Sprites.monSprites.shinyDistinction,
						"femaleDistinction": Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites?.copySprites[mon].femaleDistinction: Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction ? Dex.mod(modDex).data.Sprites.monSprites.femaleDistinction : false,
					}
				}
			}
		}
		if (Dex.mod(modDex).data.Sprites?.itemSprites !== undefined) {
			BattleTeambuilderTable.sprites[modDex]["itemSprites"] = {};
			for (const item in Dex.mod(modDex).data.Sprites.itemSprites.items) {
				BattleTeambuilderTable.sprites[modDex]["itemSprites"][item] = Dex.mod(modDex).data.Sprites.itemSprites.itemsDirectory + "/" + Dex.mod(modDex).data.Sprites.itemSprites.items[item];
			}
		}
		if (Dex.mod(modDex).data.Sprites?.typeSprites !== undefined) {
			BattleTeambuilderTable.sprites[modDex]["typeSprites"] = {};
			for (const type in Dex.mod(modDex).data.Sprites.typeSprites.types) {
				BattleTeambuilderTable.sprites[modDex]["typeSprites"][type] = Dex.mod(modDex).data.Sprites.typeSprites.typesDirectory + "/" + Dex.mod(modDex).data.Sprites.typeSprites.types[type];
			}
		}
	}
	if (Dex.mod(modDex).data.Teambuilders) {
		for (const builder of Object.keys(Dex.mod(modDex).data.Teambuilders)) {
			const builderData = Dex.mod(modDex).data.Teambuilders[builder];
			BattleTeambuilderTable[builder] = {};
			BattleTeambuilderTable[builder].mod = modDex;
			BattleTeambuilderTable[builder].formatType = builderData.formatType;
			BattleTeambuilderTable[builder].isNatDex = builderData.isNatDex;
			BattleTeambuilderTable[builder].bonusRules = builderData?.bonusRules;
			for (const format of Object.keys(builderData.formats)) {
				const formatData = builderData.formats[format];
				BattleTeambuilderTable.formats[format] = {};
				BattleTeambuilderTable.formats[format].mod = modDex;
				BattleTeambuilderTable.formats[format].builder = builder;
				BattleTeambuilderTable.formats[format].topSlice = formatData.topSlice;
				BattleTeambuilderTable.formats[format].bottomSlice = formatData?.bottomSlice;
				BattleTeambuilderTable.formats[format].defaultLevel = formatData.defaultLevel;
				BattleTeambuilderTable.formats[format].bonusRules = formatData?.bonusRules;
			}
		}
	}
}



/*********************************************************
 * Build search-index.js
 *********************************************************/

{
	process.stdout.write("Building `data/search-index.js`... ");

	let index = [];

	const BuilderMods = [];
	for (const modDex in Dex.dexes) {
		if (Dex.mod(modDex).data.Teambuilders) {
			BuilderMods.push(modDex);
		}
	}

	index = index.concat(Object.keys(Dex.data.Pokedex).map(x => x + ' pokemon'));
	for (const mod of BuilderMods) {
		for (const mon in Dex.mod(mod).data.Pokedex) {
			if (!index.includes(mon + ' pokemon')) {
				index.concat(mon + ' pokemon');
			}
		}
	}
	index = index.concat(Object.keys(Dex.data.Moves).map(x => x + ' move'));
	index = index.concat(Object.keys(Dex.data.Items).map(x => x + ' item'));
	index = index.concat(Object.keys(Dex.data.Abilities).map(x => x + ' ability'));
	index = index.concat(Object.keys(Dex.data.TypeChart).map(x => toID(x) + ' type'));
	index = index.concat(['physical', 'special', 'status'].map(x => toID(x) + ' category'));
	index = index.concat([
		'monster', 'water1', 'bug', 'flying', 'field', 'fairy', 'grass', 'humanlike', 'water3', 'mineral', 'amorphous', 'water2', 'ditto', 'dragon', 'undiscovered',
	].map(x => toID(x) + ' egggroup'));
	index = index.concat([
		'ou', 'uu', 'ru', 'nu', 'pu', 'zu', 'lc', 'nfe', 'uber', 'uubl', 'rubl', 'nubl', 'publ', 'zubl', 'cap', 'caplc', 'capnfe',
	].map(x => toID(x) + ' tier'));

	const BattleArticleTitles = {};

	try {
		for (const file of fs.readdirSync('../dex.pokemonshowdown.com/articles/')) {
			if (file.endsWith('.md')) {
				const id = file.slice(0, -3);
				const contents = '' + fs.readFileSync('../dex.pokemonshowdown.com/articles/' + file);
				if (contents.startsWith('# ')) {
					const title = contents.slice(2, contents.indexOf('\n'));
					if (title !== id.charAt(0).toUpperCase() + id.slice(1)) {
						BattleArticleTitles[id] = title;
					}
				}
				index.push('' + id + ' article');
			}
		}
	} catch {
		console.log('\n(WARNING: NO ARTICLES)');
	}
	index.push('pokemon article');
	index.push('moves article');

	const compoundTable = new Map(CompoundWordNames.map(word => [toID(word), word]));
	// generate aliases
	function generateAlias(id, name, type) {
		name = compoundTable.get(id) || name;
		if (type === 'pokemon' && !compoundTable.has(id)) {
			const species = Dex.species.get(id);
			const baseid = toID(species.baseSpecies);
			if (baseid !== id) {
				name = (compoundTable.get(baseid) || species.baseSpecies) + ' ' + species.forme;
			}
		}
		if (name.endsWith(' Mega-X') || name.endsWith(' Mega-Y')) {
			index.push('mega' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('mega' + toID(name.slice(-1)) + ' ' + type + ' ' + id + ' ' + toID(name.slice(0, -7)).length);
		} else if (name.endsWith(' Mega')) {
			index.push('mega' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Alola')) {
			index.push('alolan' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Galar')) {
			index.push('galarian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Hisui')) {
			index.push('hisuian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		}
		const fullSplit = name.split(/ |-/).map(toID);
		if (fullSplit.length < 2) return;
		const fullAcronym = fullSplit.map(x => x.charAt(0)).join('') + fullSplit.at(-1).slice(1);
		index.push('' + fullAcronym + ' ' + type + ' ' + id + ' 0');
		for (let i = 1; i < fullSplit.length; i++) {
			index.push('' + fullSplit.slice(i).join('') + ' ' + type + ' ' + id + ' ' + fullSplit.slice(0, i).join('').length);
		}

		const spaceSplit = name.split(' ').map(toID);
		if (spaceSplit.length !== fullSplit.length) {
			const spaceAcronym = spaceSplit.map(x => x.charAt(0)).join('') + spaceSplit.at(-1).slice(1);
			if (spaceAcronym !== fullAcronym) {
				index.push('' + spaceAcronym + ' ' + type + ' ' + id + ' 0');
			}
		}
	}
	for (const id in Dex.data.Pokedex) {
		const name = Dex.data.Pokedex[id].name;
		if (Dex.data.Pokedex[id].isCosmeticForme) continue;
		generateAlias(id, name, 'pokemon');
	}
	for (const id in Dex.data.Moves) {
		const name = Dex.data.Moves[id].name;
		generateAlias(id, name, 'move');
	}
	for (const id in Dex.data.Items) {
		const name = Dex.data.Items[id].name;
		generateAlias(id, name, 'item');
	}
	for (const id in Dex.data.Abilities) {
		const name = Dex.data.Abilities[id].name;
		generateAlias(id, name, 'ability');
	}

	// hardcode ultra beasts
	const ultraBeasts = {
		ub01symbiont: "nihilego",
		ub02absorption: "buzzwole",
		ub02beauty: "pheromosa",
		ub03lightning: "xurkitree",
		ub04blade: "kartana",
		ub04blaster: "celesteela",
		ub05glutton: "guzzlord",
		ubburst: "blacephalon",
		ubassembly: "stakataka",
		ubadhesive: "poipole",
		ubstinger: "naganadel",
	};
	for (const [ubCode, id] of Object.entries(ultraBeasts)) {
		index.push(`${ubCode} pokemon ${id} 0`);
	}

	index.sort();

	// manually rearrange
	index[index.indexOf('grass type')] = 'grass egggroup';
	index[index.indexOf('grass egggroup')] = 'grass type';

	index[index.indexOf('fairy type')] = 'fairy egggroup';
	index[index.indexOf('fairy egggroup')] = 'fairy type';

	index[index.indexOf('flying type')] = 'flying egggroup';
	index[index.indexOf('flying egggroup')] = 'flying type';

	index[index.indexOf('dragon type')] = 'dragon egggroup';
	index[index.indexOf('dragon egggroup')] = 'dragon type';

	index[index.indexOf('bug type')] = 'bug egggroup';
	index[index.indexOf('bug egggroup')] = 'bug type';

	index[index.indexOf('psychic type')] = 'psychic move';
	index[index.indexOf('psychic move')] = 'psychic type';

	index[index.indexOf('ditto pokemon')] = 'ditto egggroup';
	index[index.indexOf('ditto egggroup')] = 'ditto pokemon';

	const BattleSearchIndex = index.map(x => {
		x = x.split(' ');
		if (x.length > 3) {
			x[3] = Number(x[3]);
			x[2] = index.indexOf(x[2] + ' ' + x[1]);
		}
		return x;
	});

	const BattleSearchIndexOffset = BattleSearchIndex.map(entry => {
		const id = entry[0];
		let name = '';
		switch (entry[1]) {
		case 'pokemon': name = Dex.species.get(id).name; break;
		case 'move': name = Dex.moves.get(id).name; break;
		case 'item': name = Dex.items.get(id).name; break;
		case 'ability': name = Dex.abilities.get(id).name; break;
		case 'article': name = BattleArticleTitles[id] || ''; break;
		}
		let res = '';
		let nonAlnum = 0;
		for (let i = 0, j = 0; i < id.length; i++, j++) {
			while (!/[a-zA-Z0-9]/.test(name[j])) {
				j++;
				nonAlnum++;
			}
			res += nonAlnum;
		}
		if (nonAlnum) return res;
		return '';
	});

	const BattleSearchCountIndex = {};
	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' move'] = Object.keys(Dex.data.Moves)
			.filter(id => (Dex.data.Moves[id].type === type)).length;
	}

	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' pokemon'] = Object.keys(Dex.data.Pokedex)
			.filter(id => (
				!Dex.data.Pokedex[id].isCosmeticForme &&
				Dex.data.Pokedex[id].types.indexOf(type) >= 0
			)).length;
	}

	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';

	buf += 'exports.BattleSearchIndex = ' + JSON.stringify(BattleSearchIndex) + ';\n\n';

	buf += 'exports.BattleSearchIndexOffset = ' + JSON.stringify(BattleSearchIndexOffset) + ';\n\n';

	buf += 'exports.BattleSearchCountIndex = ' + JSON.stringify(BattleSearchCountIndex) + ';\n\n';

	buf += 'exports.BattleArticleTitles = ' + JSON.stringify(BattleArticleTitles) + ';\n\n';

	fs.writeFileSync('play.pokemonshowdown.com/data/search-index.js', buf);
}

console.log("DONE");

/*********************************************************
 * Build teambuilder-tables.js
 *********************************************************/

process.stdout.write("Building `data/teambuilder-tables.js`... ");

{

	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';
	// process.stdout.write("\n  ");
	for (const tableKey of Object.keys(BattleTeambuilderTable)) {
		if (tableKey === "formats" || tableKey === "sprites") {
			continue;
		}
		const gen = BattleTeambuilderTable[tableKey]["mod"];
		const genTable = Dex.mod(gen).data.Teambuilders[tableKey];
		const pokemon = Object.keys(Dex.mod(gen).data.Pokedex);
		pokemon.sort();
		const tierTable = {};
		const overrideTier = {};
		const metagameBans = {};
		const nonstandardMoves = [];
		for (const id of pokemon) {
			const species = Dex.mod(gen).species.get(id);
			if (species.gen > Dex.mod(gen).data.Scripts.gen) continue;
			const speciesTier = (() => {
				const tempTier = genTable.tierType === "tier" ? species.tier: genTable.tierType === "doublesTier" ? species.doublesTier: species.natDexTier;
				if (genTable.validTiers.includes(tempTier)) {
					return tempTier;
				} else {
					return 'Illegal';
				}
			})();
			overrideTier[species.id] = speciesTier;
			if (!tierTable[speciesTier]) tierTable[speciesTier] = [];
			tierTable[speciesTier].push(id);
		}

		const tiers = [];
		const items = [];
		const formatSlices = {};


		BattleTeambuilderTable[tableKey].learnsets = {};
		BattleTeambuilderTable[tableKey].tiers = tiers;
		BattleTeambuilderTable[tableKey].items = items;
		BattleTeambuilderTable[tableKey].overrideTier = overrideTier;
		BattleTeambuilderTable[tableKey].formatSlices = formatSlices;
		BattleTeambuilderTable[tableKey].formatNames = genTable.formats;

		let tierOrder = [];

		if (genTable.validTiers) {
			tierOrder = genTable.validTiers;
		} else {
			tierOrder = [ "CAP", "CAP NFE", "CAP LC", "AG", "Uber", "(Uber)", "OU", "(OU)", "UUBL", "UU",
				"RUBL", "RU", "NUBL", "NU", "PUBL", "PU", "ZUBL", "ZU", "New", "NFE", "LC", "Unreleased"];
		}

		for (const tier of tierOrder) {
			formatSlices[tier] = tiers.length;
			if (!tierTable[tier]) continue;
			tiers.push(['header', tier]);
			tiers.push(...tierTable[tier]);
		}

		const itemList = Object.keys(Dex.mod(gen).data.Items);
		itemList.sort();

		const greatItems = [['header', "Popular items"]];
		const goodItems = [['header', "Items"]];
		const specificItems = [['header', "Pok\u00e9mon-specific items"]];
		const poorItems = [['header', "Usually useless items"]];
		const badItems = [['header', "Useless items"]];
		const unreleasedItems = [];
		if (Dex.mod(gen).data.Scripts.gen === 6) unreleasedItems.push(['header', "Unreleased"]);

		for (const id of itemList) {
			const item = Dex.mod(gen).items.get(id);
			if (item.gen > Dex.mod(gen).data.Scripts.gen) {
				continue;
			}
			if (item.isNonstandard) {
				if (genTable.isNatDex) {
					let curItem = item;
					let curGen = Dex.mod(gen).data.Scripts.gen;
					while (curItem.isNonstandard && curGen >= 7) {
						curItem = Dex.forGen(curGen).items.get(item.id);
						curGen--;
					}
					if (curItem.isNonstandard) {
						continue;
					}
				} else if (Dex.mod(gen).data.Scripts.gen !== 2) {
					continue;
				}
			}
			switch (id) {
				// mainstays
				case 'choiceband':
				case 'choicespecs':
				case 'eviolite':
					greatItems.push(id);
					break;
				// great everywhere but metronome
				case 'leftovers':
				case 'lifeorb':
				case 'choicescarf':
				case 'assaultvest':
				case 'focussash':
				case 'powerherb':
				case 'rockyhelmet':
					greatItems.push(id)
					break;
				// just singles
				case 'airballoon':
				case 'loadeddice':
				case 'heavydutyboots':
				case 'expertbelt':
				case 'salacberry':
					if (genTable.formatType === "doubles") goodItems.push(id);
					else greatItems.push(id);
					break;
				// just doubles
				case 'safetygoggles':
				case 'ejectbutton':
				case 'ejectpack':
					if (genTable.formatType === "doubles") greatItems.push(id);
					else goodItems.push(id);
					break;
				// doubles + metronome
				case 'covertcloak':
				case 'clearamulet':
				case 'weaknesspolicy':
					if (genTable.formatType === "doubles") greatItems.push(id);
					else goodItems.push(id);
					break;
				// metronome only
				case 'mirrorherb':
					goodItems.push(id);
					break;
				// generation specific
				case 'mentalherb':
					if (Dex.mod(gen).data.Scripts.gen > 4) greatItems.push(id);
					else poorItems.push(id);
					break;
				case 'lumberry':
					if (Dex.mod(gen).data.Scripts.gen === 2 || Dex.mod(gen).data.Scripts.gen > 6) goodItems.push(id);
					else greatItems.push(id);
					break;
				case 'sitrusberry':
					if (Dex.mod(gen).data.Scripts.gen > 3 && (Dex.mod(gen).data.Scripts.gen < 7 || genTable.formatType === "doubles")) greatItems.push(id);
					else if (Dex.mod(gen).data.Scripts.gen > 6) goodItems.push(id);
					else poorItems.push(id);
					break;
				case 'aguavberry':
				case 'figyberry':
				case 'iapapaberry':
				case 'magoberry':
				case 'wikiberry':
					if (Dex.mod(gen).data.Scripts.gen === 7) greatItems.push(id);
					else if (Dex.mod(gen).data.Scripts.gen >= 8) goodItems.push(id);
					else poorItems.push(id);
					break;
				case 'berryjuice':
					if (Dex.mod(gen).data.Scripts.gen === 2) poorItems.push(id);
					else goodItems.push(id);
					break;
				case 'dragonfang':
					if (Dex.mod(gen).data.Scripts.gen === 2) badItems.push(id);
					else goodItems.push(id);
					break;
				case 'dragonscale':
					if (Dex.mod(gen).data.Scripts.gen === 2) goodItems.push(id);
					else badItems.push(id);
					break;
				case 'mail':
					if (Dex.mod(gen).data.Scripts.gen >= 6) unreleasedItems.push(id);
					else goodItems.push(id);
					break;
				// Legendaries
				case 'adamantorb':
				case 'griseousorb':
				case 'lustrousorb':
				case 'blueorb':
				case 'redorb':
				case 'souldew':
				// falls through
				// Other
				case 'leek':
				case 'stick':
				case 'thickclub':
				case 'lightball':
				case 'luckypunch':
				case 'quickpowder':
				case 'metalpowder':
				case 'deepseascale':
				case 'deepseatooth':
					specificItems.push(id);
					break;
				// Fling-only
				case 'rarebone':
				case 'belueberry':
				case 'blukberry':
				case 'cornnberry':
				case 'durinberry':
				case 'hondewberry':
				case 'magostberry':
				case 'nanabberry':
				case 'nomelberry':
				case 'pamtreberry':
				case 'pinapberry':
				case 'pomegberry':
				case 'qualotberry':
				case 'rabutaberry':
				case 'razzberry':
				case 'spelonberry':
				case 'tamatoberry':
				case 'watmelberry':
				case 'wepearberry':
				case 'energypowder':
				case 'electirizer':
				case 'oldamber':
				case 'dawnstone':
				case 'dubiousdisc':
				case 'duskstone':
				case 'firestone':
				case 'icestone':
				case 'leafstone':
				case 'magmarizer':
				case 'moonstone':
				case 'ovalstone':
				case 'prismscale':
				case 'protector':
				case 'reapercloth':
				case 'sachet':
				case 'shinystone':
				case 'sunstone':
				case 'thunderstone':
				case 'upgrade':
				case 'waterstone':
				case 'whippeddream':
				case 'bottlecap':
				case 'goldbottlecap':
				case 'galaricacuff':
				case 'chippedpot':
				case 'crackedpot':
				case 'galaricawreath':
				case 'auspiciousarmor':
				case 'maliciousarmor':
				case 'masterpieceteacup':
				case 'metalalloy':
				case 'unremarkableteacup':
				case 'bignugget':
					badItems.push(id);
					break;
				// outclassed items
				case 'aspearberry':
				case 'bindingband':
				case 'cheriberry':
				case 'destinyknot':
				case 'enigmaberry':
				case 'floatstone':
				case 'ironball':
				case 'jabocaberry':
				case 'oranberry':
				case 'machobrace':
				case 'pechaberry':
				case 'persimberry':
				case 'poweranklet':
				case 'powerband':
				case 'powerbelt':
				case 'powerbracer':
				case 'powerlens':
				case 'powerweight':
				case 'rawstberry':
				case 'ringtarget':
				case 'rowapberry':
				case 'bigroot':
				case 'focusband':
				// gen 2
				case 'psncureberry':
				case 'przcureberry':
				case 'burntberry':
				case 'bitterberry':
				case 'iceberry':
				case 'berry':
					poorItems.push(id);
					break;
				default:
					if (
						item.name.endsWith(" Ball") || item.name.endsWith(" Fossil") || item.name.startsWith("Fossilized ") ||
						item.name.endsWith(" Sweet") || item.name.endsWith(" Apple")
					) {
						badItems.push(id);
					} else if (item.name.startsWith("TR")) {
						if (genTable.bonusRules !== undefined && 'Broken Record' in genTable.bonusRules) {
							console.log("Broken Record Spotted");
							goodItems.push(id);
						}
						else {
							badItems.push(id);
						}
					} else if (item.name.endsWith(" Gem") && item.name !== "Normal Gem") {
						if (Dex.mod(gen).data.Scripts.gen >= 6) {
							unreleasedItems.push(id);
						} else {
							goodItems.push(id);
						}
					} else if (item.name.endsWith(" Drive")) {
						specificItems.push(id);
					} else if (item.name.endsWith(" Memory")) {
						specificItems.push(id);
					} else if (item.name.startsWith("Rusted")) {
						specificItems.push(id);
					} else if (item.itemUser) {
						specificItems.push(id);
					} else if (item.megaStone) {
						specificItems.push(id);
					} else {
						goodItems.push(id);
					}
			}
		}
		items.push(...greatItems);
		items.push(...goodItems);
		items.push(...specificItems);
		items.push(...poorItems);
		items.push(...badItems);
		items.push(...unreleasedItems);
	}

	//
	// Learnset table
	//

	const gen3HMs = new Set(['cut', 'fly', 'surf', 'strength', 'flash', 'rocksmash', 'waterfall', 'dive']);
	const gen4HMs = new Set(['cut', 'fly', 'surf', 'strength', 'rocksmash', 'waterfall', 'rockclimb']);

	for (const tableKey of Object.keys(BattleTeambuilderTable)) {
		if (tableKey === "formats" || tableKey === "sprites") {
			continue;
		}
		const gen = BattleTeambuilderTable[tableKey]["mod"];
		const ModLearnsets = Dex.mod(gen).data.Learnsets;
		for (const id in ModLearnsets) {
			if (BattleTeambuilderTable[tableKey].overrideTier[id] === "Illegal") {
				continue;
			}
			const learnset = ModLearnsets[id].learnset;
			if (!learnset) continue;
			BattleTeambuilderTable[tableKey].learnsets[id] = {};
			for (const moveid in learnset) {
				const gens = learnset[moveid].map(x => Number(x[0]));
				const minGen = Math.min(...gens);

				if (minGen <= 4 && (gen3HMs.has(moveid) || gen4HMs.has(moveid))) {
					let legalGens = '';
					let available = false;

					if (minGen === 3) {
						legalGens += '3';
						available = true;
					}
					if (available) available = !gen3HMs.has(moveid);

					if (available || gens.includes(4)) {
						legalGens += '4';
						available = true;
					}
					if (available) available = !gen4HMs.has(moveid);

					const minUpperGen = available ? 5 : Math.min(
						...gens.filter(gen => gen > 4)
					);
					legalGens += '0123456789'.slice(minUpperGen);
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] = legalGens;
				} else {
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] = '0123456789'.slice(minGen);
				}

				if (gens.indexOf(6) >= 0) {
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] += 'p';
				}
				if (gens.indexOf(7) >= 0 && learnset[moveid].some(x => x[0] === '7' && x !== '7V')) {
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] += 'q';
				}
				if (gens.indexOf(8) >= 0 && learnset[moveid].some(x => x[0] === '8' && x !== '8V')) {
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] += 'g';
				}
				if (gens.indexOf(9) >= 0 && learnset[moveid].some(x => x[0] === '9' && x !== '9V')) {
					BattleTeambuilderTable[tableKey].learnsets[id][moveid] += 'a';
				}
			}
		}
	}

	// Client relevant data that should be overriden by past gens and mods
	const overrideSpeciesKeys = [
		'abilities', 'baseStats', 'cosmeticFormes', 'isNonstandard', 'requiredItems', 'types', 'unreleasedHidden',
	];
	const overrideMoveKeys = [
		'accuracy', 'basePower', 'category', 'desc', 'flags', 'isNonstandard', 'pp', 'priority', 'shortDesc', 'target', 'type',
	];
	const overrideAbilityKeys = ['desc', 'flags', 'isNonstandard', 'rating', 'shortDesc'];
	const overrideItemKeys = ['desc', 'fling', 'isNonstandard', 'naturalGift', 'shortDesc', 'relevantTiers'];

	//
	// Mods
	//

	for (const tableKey of Object.keys(BattleTeambuilderTable)) {
		if (tableKey === "formats" || tableKey === "sprites") {
			continue;
		}
		const gen = BattleTeambuilderTable[tableKey]["mod"];
		const modDex = Dex.mod(gen);
		const modData = modDex.data;
		const parentDex = Dex.forGen(modDex.gen);

		const overrideSpeciesData = {};
		BattleTeambuilderTable[tableKey].overrideSpeciesData = overrideSpeciesData;
		for (const id in modData.Pokedex) {
			const modEntry = modDex.species.get(id);
			const parentEntry = parentDex.species.get(id);
			for (const key of overrideSpeciesKeys) {
				if (JSON.stringify(modEntry[key]) !== JSON.stringify(parentEntry[key])) {
					if (!overrideSpeciesData[id]) overrideSpeciesData[id] = {};
					overrideSpeciesData[id][key] = modEntry[key];
				}
			}
		}

		const overrideMoveData = {};
		BattleTeambuilderTable[tableKey].overrideMoveData = overrideMoveData;
		for (const id in modData.Moves) {
			const modEntry = modDex.moves.get(id);
			const parentEntry = parentDex.moves.get(id);
			for (const key of overrideMoveKeys) {
				if (key === 'category' && modDex.gen <= 3) continue;
				if (JSON.stringify(modEntry[key]) !== JSON.stringify(parentEntry[key])) {
					if (!overrideMoveData[id]) overrideMoveData[id] = {};
					overrideMoveData[id][key] = modEntry[key];
				}
			}
		}

		const overrideAbilityData = {};
		BattleTeambuilderTable[tableKey].overrideAbilityData = overrideAbilityData;
		for (const id in modData.Abilities) {
			const modEntry = modDex.abilities.get(id);
			const parentEntry = parentDex.abilities.get(id);
			for (const key of overrideAbilityKeys) {
				if (JSON.stringify(modEntry[key]) !== JSON.stringify(parentEntry[key])) {
					if (!overrideAbilityData[id]) overrideAbilityData[id] = {};
					overrideAbilityData[id][key] = modEntry[key];
				}
			}
		}

		const overrideItemData = {};
		BattleTeambuilderTable[tableKey].overrideItemData = overrideItemData;
		for (const id in modData.Items) {
			const modEntry = modDex.items.get(id);
			const parentEntry = parentDex.items.get(id);
			for (const key of overrideItemKeys) {
				if (JSON.stringify(modEntry[key]) !== JSON.stringify(parentEntry[key])) {
					if (!overrideItemData[id]) overrideItemData[id] = {};
					overrideItemData[id][key] = modEntry[key];
				}
			}
		}
	}

	buf += `exports.BattleTeambuilderTable = JSON.parse('${JSON.stringify(BattleTeambuilderTable).replace(/['\\]/g, "\\$&")}');\n\n`;

	fs.writeFileSync('play.pokemonshowdown.com/data/teambuilder-tables.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/teambuilder-tables.json', JSON.stringify(BattleTeambuilderTable));
}

console.log("DONE");

/*********************************************************
 * Build pokedex.js
 *********************************************************/

process.stdout.write("Building `data/pokedex.js`... ");

{
	const Pokedex = requireNoCache('../caches/pokemon-showdown/dist/data/pokedex.js').Pokedex;
	for (const id in Pokedex) {
		const entry = Pokedex[id];
		if (Dex.data.FormatsData[id]) {
			const formatsEntry = Dex.data.FormatsData[id];
			if (formatsEntry.tier) entry.tier = formatsEntry.tier;
			if (formatsEntry.isNonstandard) entry.isNonstandard = formatsEntry.isNonstandard;
			if (formatsEntry.unreleasedHidden) entry.unreleasedHidden = formatsEntry.unreleasedHidden;
		}
	}

	const BuilderMods = [];
	for (const modDex in Dex.dexes) {
		if (Dex.mod(modDex).data.Teambuilders) {
			BuilderMods.push(modDex);
		}
	}
	for (const gen of BuilderMods) {
		for (const id in Dex.mod(gen).data.Pokedex) {
			if (id in Pokedex) {
				continue;
			}
			else {
				Pokedex[id] = Dex.mod(gen).data.Pokedex[id];
				Pokedex[id].isModded = true;
			}
		}
	}

	const buf = 'exports.BattlePokedex = ' + es3stringify(Pokedex) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/pokedex.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/pokedex.json', JSON.stringify(Pokedex));
}

console.log("DONE");

/*********************************************************
 * Build moves.js
 *********************************************************/

process.stdout.write("Building `data/moves,items,abilities,typechart,learnsets.js`...");

{
	const Moves = requireNoCache('../caches/pokemon-showdown/dist/data/moves.js').Moves;
	for (const id in Moves) {
		const move = Dex.moves.get(Moves[id].name);
		if (move.desc) Moves[id].desc = move.desc;
		if (move.shortDesc) Moves[id].shortDesc = move.shortDesc;
		if (move.basePowerCallback) Moves[id].basePowerCallback = true;
	}

	const BuilderMods = [];
	for (const modDex in Dex.dexes) {
		if (Dex.mod(modDex).data.Teambuilders) {
			BuilderMods.push(modDex);
		}
	}
	for (const gen of BuilderMods) {
		for (const id in Dex.mod(gen).data.Moves) {
			if (id in Moves) {
				continue;
			}
			else {
				Moves[id] = Dex.mod(gen).data.Moves[id];
			}
		}
	}

	const buf = 'exports.BattleMovedex = ' + es3stringify(Moves) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/moves.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/moves.json', JSON.stringify(Moves));
}

/*********************************************************
 * Build items.js
 *********************************************************/

{
	const Items = requireNoCache('../caches/pokemon-showdown/dist/data/items.js').Items;
	for (const id in Items) {
		const item = Dex.items.get(Items[id].name);
		if (item.desc) Items[id].desc = item.desc;
		if (item.shortDesc) Items[id].shortDesc = item.shortDesc;
	}

	const BuilderMods = [];
	for (const modDex in Dex.dexes) {
		if (Dex.mod(modDex).data.Teambuilders) {
			BuilderMods.push(modDex);
		}
	}
	for (const gen of BuilderMods) {
		for (const id in Dex.mod(gen).data.Items) {
			if (id in Items) {
				continue;
			}
			else {
				Items[id] = Dex.mod(gen).data.Items[id];
			}
		}
	}
	const buf = 'exports.BattleItems = ' + es3stringify(Items) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/items.js', buf);
}

/*********************************************************
 * Build abilities.js
 *********************************************************/

{
	const Abilities = requireNoCache('../caches/pokemon-showdown/dist/data/abilities.js').Abilities;
	for (const id in Abilities) {
		const ability = Dex.abilities.get(Abilities[id].name);
		if (ability.desc) Abilities[id].desc = ability.desc;
		if (ability.shortDesc) Abilities[id].shortDesc = ability.shortDesc;
	}

	const BuilderMods = [];
	for (const modDex in Dex.dexes) {
		if (Dex.mod(modDex).data.Teambuilders) {
			BuilderMods.push(modDex);
		}
	}
	for (const gen of BuilderMods) {
		for (const id in Dex.mod(gen).data.Abilities) {
			if (id in Abilities) {
				continue;
			}
			else {
				Abilities[id] = Dex.mod(gen).data.Abilities[id];
			}
		}
	}
	const buf = 'exports.BattleAbilities = ' + es3stringify(Abilities) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/abilities.js', buf);
}

/*********************************************************
 * Build typechart.js
 *********************************************************/

{
	const TypeChart = requireNoCache('../caches/pokemon-showdown/dist/data/typechart.js').TypeChart;
	const buf = 'exports.BattleTypeChart = ' + es3stringify(TypeChart) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/typechart.js', buf);
}

/*********************************************************
 * Build aliases.js
 *********************************************************/

{
	const Aliases = requireNoCache('../caches/pokemon-showdown/dist/data/aliases.js').Aliases;
	const buf = 'exports.BattleAliases = ' + es3stringify(Aliases) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/aliases.js', buf);
}

/*********************************************************
 * Build formats-data.js
 *********************************************************/

{
	const FormatsData = requireNoCache('../caches/pokemon-showdown/dist/data/formats-data.js').FormatsData;
	const buf = 'exports.BattleFormatsData = ' + es3stringify(FormatsData) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/formats-data.js', buf);
}

/*********************************************************
 * Build formats.js
 *********************************************************/

{
	const Formats = requireNoCache('../caches/pokemon-showdown/dist/config/formats.js').Formats;
	const buf = 'exports.Formats = ' + es3stringify(Formats) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/formats.js', buf);
}

/*********************************************************
 * Build learnsets.js
 *********************************************************/

{
	const Learnsets = requireNoCache('../caches/pokemon-showdown/dist/data/learnsets.js').Learnsets;
	const buf = 'exports.BattleLearnsets = ' + es3stringify(Learnsets) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/learnsets.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/learnsets.json', JSON.stringify(Learnsets));
}

/*********************************************************
 * Build text.js
 *********************************************************/

{
	const textData = Dex.loadTextData();
	const Text = textData.Default;

	function assignData(id, entry) {
		for (const key in entry) {
			if (['name', 'desc', 'shortDesc'].includes(key)) continue;
			const textEntry = Text[id] || (Text[id] = {});
			if (key.startsWith('gen')) {
				for (const modKey in entry[key]) {
					if (['desc', 'shortDesc'].includes(key)) continue;
					textEntry[modKey + 'Gen' + key.charAt(3)] = entry[key][modKey];
				}
			} else {
				textEntry[key] = entry[key];
			}
		}
	}

	for (const id in textData.Moves) assignData(id, textData.Moves[id]);
	for (const id in textData.Abilities) assignData(id, textData.Abilities[id]);
	for (const id in textData.Items) assignData(id, textData.Items[id]);

	const buf = 'exports.BattleText = ' + es3stringify(Text) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/text.js', buf);
}

console.log("DONE");
